### ISSUE TITLE
Please support breakpoint resume download Feature

### ISSUE THREAD

**Issue by marvinpan8** [rgreinho/trauma#17]
# Please support breakpoint resume download Feature

**Comment by rgreinho** [comment]
That's definitely a needed feature for the next version!

Implementation resources:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
- https://kean.blog/post/resumable-downloads

**Comment by rgreinho** [comment]
@marvinpan8 Here is the PR in case you want a sneak preview and/or submit feedback: https://github.com/rgreinho/trauma/pull/26
