### ISSUE TITLE
Get the status of the files downloaded or are in progress of downloading

### ISSUE THREAD

**Issue by akashlama1998-icloud** [rgreinho/trauma#42]
I'm kind of annoyed by myself asking all these question which may be silly. Because I'm kind of new to rust. And thanks to people like you I find the community really helpful and kind. This time I want to ask about if it is possible to get the status of files which are in progress or even if I which files are downloaded like a vector of statuses 🤞🤔. So that I can show the child progress bar with the file name, or if you figure out that if we can disable child progress bars, then showing the currently downloading file name in the main progress bar. Thank you in advance man you did helped me a lot 🙏🙏

**Comment by rgreinho** [comment]
The [with-report](https://github.com/rgreinho/trauma/blob/main/examples/with-report.rs) example shows one way to use the download report. That may help you a little.

However the report is only made available at the end of the download process. Returning the statuses as it goes might be possible, but that would require changing the Trauma design.

**Comment by crisqyxw** [comment]
> The [with-report](https://github.com/rgreinho/trauma/blob/main/examples/with-report.rs) example shows one way to use the download report. That may help you a little.
> 
> However the report is only made available at the end of the download process. Returning the statuses as it goes might be possible, but that would require changing the Trauma design.

Sorry but does this mean that getting the download progress in real time via a callback function or whatever is not going to be implemented? I think it's a necessary feature for developing GUI apps...
