### ISSUE TITLE
Custom Http Headers

### ISSUE THREAD

**Issue by 2moe** [rgreinho/trauma#52]
## Problem

Some websites restrict the UA, so if it is an invalid UA (null UA or IE), then it will deny service.  
So I need the ua header.

When I used `trauma::downloader::DownloaderBuilder`, I found that I could not add headers directly.

___

```rust
const FIREFOX_UA: &str =
    "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0";
let ua = http::header::HeaderValue::from_str(FIREFOX_UA)?;
```

https://github.com/rgreinho/trauma/blob/a5f5bb77602ef1c4f15051a60557b00e54028d6b/src/downloader.rs#L156-L161

It is not difficult to add the header.

```rust
req = req.headers(HeaderMap::from_iter([(http::header::USER_AGENT, ua)]));
```

But I had to modify the trauma lib, instead of using `DownloaderBuilder::new().headers(...)`.

Incidentally, I think it should also support custom filename, instead of relying entirely on `form_urlencoded` to automatically parse

https://github.com/rgreinho/trauma/blob/a5f5bb77602ef1c4f15051a60557b00e54028d6b/src/downloader.rs#L27-L38

```rust
filename: Option<OsString>,
headermap: Option<HeaderMap>,
```

**Comment by rgreinho** [comment]
Oh I see! That's a good idea for a feature to add. Do you happen to have a PR I could review by any chance?

Regarding the custom filename, this feature already exists. You can look at the [Download::new()](https://docs.rs/trauma/latest/trauma/download/struct.Download.html#method.new) method. It allows you to pass a custom name to the download.
