### ISSUE TITLE
All files skipped

### ISSUE THREAD

**Issue by Aurillium** [rgreinho/trauma#55]
# Bug Report

All the files I try to download happen instantly, but then the summary says they're skipped. This happens in all cases, including the `simple.rs` example.

The simple example output:
https://pastebin.com/Vh0tCgrE

## Current Behavior

Files are not being downloaded; reported as skipped.

## Expected Behavior

Files should be downloaded.

## Possible Solution

I'm still pretty clueless why this is happening. I would at least like to be able to disable skipping in the downloader builder though because that would bypass the issue for me. A proper fix would be better though.

## Steps to Reproduce

1. Create a new cargo package
2. Add `tokio` with full features and `trauma`
3. Paste the `simple.rs` example in `src/main.rs`
4. Change line 11 (`downloader.download(&downloads).await`) to `println!("{:#?}", downloader.download(&downloads).await);` in order to print summaries for debugging
5. `cargo run`

## Context

I was trying to download the example file with the example script (my end goal was download the game Factorio; I'd logged in from `reqwest` and was initially using the cookie from the login to download with `trauma`, but this bug exists on a clean project using only the `simple.rs` example code).

### Last commit:

[d46c5e8](https://github.com/rgreinho/trauma/commit/d46c5e8ea123ebe374b63f57b28fb172c9c24a8d): Prepare the code base for 2.2.0 release ([#54](https://github.com/rgreinho/trauma/pull/54))

### Browser(s):

Mozilla Firefox 110.0.1

### System Version:

Ubuntu 22.10

**Comment by Aurillium** [comment]
I've worked out the root cause of this issue and submitted a pull request which solves it ([pull request #56](https://github.com/rgreinho/trauma/pull/56))

**Comment by rgreinho** [comment]
To add to this bug report, the problem happens when the server does not return the `content-length` in the header.

**Comment by rgreinho** [comment]
Fixed by #56. Thanks a lot @Aurillium .
