### ISSUE TITLE
Resume download indicator show wrong total file size

### ISSUE THREAD

**Issue by Latias94** [rgreinho/trauma#59]
# Bug Report

Every time I resume the canceled ddownload task, the indicator show wrong total size. The true total size of that file should be round to 500 mb.

## Current Behavior

```rust
pub const ASSET_PACK_URL: &str = "http://vulkan.gpuinfo.org/downloads/vulkan_asset_pack_gltf.zip";

// ...
let downloads = vec![Download::try_from(ASSET_PACK_URL).unwrap()];

let downloader = DownloaderBuilder::new()
    .directory(PathBuf::from("./"))
    .build();
downloader.download(&downloads).await;
```

![image](https://user-images.githubusercontent.com/13315417/232226826-4f78bb7e-cf7f-4a08-ba23-dc949b9667d0.png)

## Expected Behavior

show right total file size

## Possible Solution

Is it caused by this header?

```rust
if self.resumable && can_resume {
    req = req.header(RANGE, format!("bytes={}-", size_on_disk));
}
```

## Steps to Reproduce

1. download
2. cancel
3. download again

## Your Environment

```bash
trauma = "2.2.1"
System Version: Win11
```

**Comment by rgreinho** [comment]
Thank you for submitting the issue!

I will have to dig a little, but at first, it seems like trauma displays only the size left to download, whereas it should display the amount of bytes already downloaded + what's left to download.

**Comment by rgreinho** [comment]
The issue should be resolved, as per the screenshot bellow (the 2 first runs are without the patch, and the last one after the patch).

![Screenshot 2023-04-26 at 8 51 32 AM](https://user-images.githubusercontent.com/6969134/234597664-ae3af1ff-3531-44ef-aca7-979bdce81cc4.png)

I'll release version 2.2.2 shortly with this fix. Thanks again for reporting the problem.
