### ISSUE TITLE
Set custom headers for checking is_resumable

### ISSUE THREAD

**Issue by jf908** [rgreinho/trauma#62]
# Feature request

## Current Behavior

At the moment is_resumable uses a HEAD request with no headers so requests requiring basic auth aren't resumable.

## Possible Solution

I think the HEAD request should be sent with the same headers as the main GET request. There could potentially be reasons why you would want to send it with separate headers for each but I cannot think of any right now.

**Comment by rgreinho** [comment]
Thanks for reporting the issue 👍 

It should not be too difficult to fix, probably as simple as setting the default headers when we create the client or something like that. I'll need to dig a little, but would you happen to have an example I could use to reproduce the problem by any chance?

**Comment by jf908** [comment]
This solved my problem, thanks!
