### ISSUE TITLE
How to format download progress

### ISSUE THREAD

**Issue by basicfunc** [rgreinho/trauma#70]
# Help request

Hey, I am currently developing a package manager and utilizing a `trauma` to manage downloads. However, I am facing difficulties in formatting the download progress as per my requirements. Properly formatted download progress is crucial for the functionality and user experience of my package manager.

Currently it is:
![image](https://github.com/rgreinho/trauma/assets/84739019/eed22f47-d0bd-4cc4-95d8-1b1b81a019c8)

Whereas I want it to look like:
![image](https://github.com/rgreinho/trauma/assets/84739019/dd402f44-f88a-4974-8704-4e61d1efcae1)
(I don't want progress bar made of hashes, PIP like progeress bar is great)

How can I format download as I want?

**Comment by rgreinho** [comment]
If you look at the [with-style.rs](https://github.com/rgreinho/trauma/blob/main/examples/with-style.rs#L21) example it may help you achieve what you want.

If I understand correctly, you want to flip the position of the items. The `ProgressBarOpts` object gives you the ability to do so by modifying the template: https://github.com/rgreinho/trauma/blob/main/examples/with-style.rs#L35-L43. The default template has the following format: https://github.com/rgreinho/trauma/blob/main/src/downloader.rs#L507-L511.

The items come directly from the [indicatif](https://github.com/console-rs/indicatif) library. You may find more items that you need in their documentation: https://docs.rs/indicatif/latest/indicatif/#templates

**Comment by basicfunc** [comment]
Thanks I will look into it
